select * from customer limit 20;

-- 1) What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as total_revenue_generated 
from customer
group by gender;

-- 2) Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and
purchase_amount >= (select avg(purchase_amount) from customer);

-- 3) Which are the top 5 products with the highest average review rating?

with cte as (
select item_purchased, ROUND(avg(review_rating::numeric),2) as average_review_rating
from customer
group by item_purchased order by avg(review_rating::numeric) desc
)
select * from cte limit 5;

-- 4) Compare the average purchase amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount), 2)
from customer
group by shipping_type 
having shipping_type in ('Standard', 'Express');

-- 5) Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status as is_subscribed, 
ROUND(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend;

-- 6) Which 5 products have the highest percentage of purchases with discounts applied?

with cte as (
select item_purchased,
count(item_purchased) as total_count
from customer
where discount_applied = 'Yes'
group by item_purchased)

select item_purchased,
ROUND(100 * total_count / sum(total_count) OVER (), 2) as purchase_percentage
from cte
order by purchase_percentage desc
limit 5;

-- 7) Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with cte as(
select customer_id,  previous_purchases,
case 
	when previous_purchases <=1 THEN 'New'
	when previous_purchases between 2 and 10 THEN 'Returning'
	when previous_purchases >10 THEN 'Loyal'
end as customer_type
from customer)

select customer_type, count(*)
from cte
group by customer_type;

-- 8) What are the top 3 most purchased products within each category?

with cte as(
select category, item_purchased,
ROW_NUMBER() OVER (partition by category order by count(item_purchased) desc) as productrank
from customer
group by category, item_purchased)

select * from cte
where productrank <=3;

-- 9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id)
from customer
where previous_purchases > 5
group by subscription_status;

-- 10) What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;

